---
name: Lint Checks
"on":
  push:
    branches: ["**"]
    paths:
      - "web/**"
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    paths:
      - "web/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
